#!/bin/sh

while :
  do
    # If the broker is unreachable mosquitto_sub exits at once: wait instead of respawning it
    # in a tight loop for as long as the broker is down.
    RXCMD=$(/usr/bin/mosquitto_sub -C 1 --will-topic ${LASTWILLTOPIC} --will-payload offline -h ${BROKERADDR} -t ${RXTOPIC}) || { /bin/sleep 5; continue; }
    echo "$RXCMD" | nc 0 30006
  done
